### ISSUE TITLE
Remnant Core Todo List

### ISSUE THREAD

**Issue by name1e5s** [name1e5s/Remnant#1]
- [ ] Frontend
    - [ ] Next PC generation
    - [ ] Simple ICache
    - [ ] TLB support
    - [ ] Branch predictor
        - [ ] Common interface
        - [ ] GShare predictor
        - [ ] Tournament predictor (21264)
        - [ ] BTB
        - [ ] RAS
    - [ ] Instruction buffer
    Also as loop buffer ?
- [ ] Decoder
- [ ] Regiser renaming
    - [ ] RAM based map table
    - [ ] Free list
    - [ ] Busy table
- [ ] Issue Unit
    - [ ] Interface
    - [ ] FPGA optimized implementation
- [ ] Functional Unit
    - [ ] Common Interface
    - [ ] Branch unit
    - [ ] Simple ALU
        - [ ] Interface
        - [ ] Bypass network
        - [x] Inner Unit
    - [ ] MDU
        - [ ] Interface
        - [ ] Inner Unit
            - [x] For simulation
            - [ ] FPGA
    - [ ] LSU
        - [ ] Address generation
        - [ ] Queues
        - [ ] Simple DCache
        - [ ] TLB support
        - [ ] Store Buffer
        - [ ] CP0 as load-store operation
- [ ] Register File
- [ ] ROB
- [ ] Documentation
